"""empty message

Revision ID: f3344b373e7b
Revises: cefb6574cfaa
Create Date: 2019-05-09 14:45:16.971924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3344b373e7b'
down_revision = 'cefb6574cfaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_series', 'series', ['series_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_series', type_='foreignkey')
        batch_op.create_foreign_key(None, 'series', ['series_id'], ['id'])

    # ### end Alembic commands ###
